In [9]:
import pandas as pd
file_name = "KM6312.csv"
pd.read_csv("C:\\users\范思源\Desktop\KM6312\KM6312.csv")

,year,Country Name,region,developing_or_developed,happiness_score,gdp_per_capita,social_support,hearlthy_life_expentancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,PDI,IDV,MAS,UAI,LTO,Indulgence
0,2015,Albania,Central and Eastern Europe,developing,4.9590,0.878670,0.804340,0.813250,0.357330,0.142720,0.064130,90,20,80,70,61,15
1,2016,Albania,Central and Eastern Europe,developing,4.6550,0.955300,0.501630,0.730070,0.318660,0.168400,0.053010,90,20,80,70,61,15
2,2017,Albania,Central and Eastern Europe,developing,4.6440,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,90,20,80,70,61,15
3,2018,Albania,Central and Eastern Europe,developing,4.5860,0.916000,0.817000,0.790000,0.419000,0.149000,0.032000,90,20,80,70,61,15
4,2019,Albania,Central and Eastern Europe,developing,4.7190,0.947000,0.848000,0.874000,0.383000,0.178000,0.027000,90,20,80,70,61,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801,2019,Zambia,Sub-Saharan Africa,developing,4.1070,0.578000,1.058000,0.426000,0.431000,0.247000,0.087000,60,35,40,50,30,42
802,2020,Zambia,Sub-Saharan Africa,developing,3.7594,0.536834,0.896037,0.363593,0.491318,0.250621,0.086705,60,35,40,50,30,42
803,2021,Zambia,Sub-Saharan Africa,developing,4.0730,0.528000,0.552000,0.231000,0.487000,0.227000,0.074000,60,35,40,50,30,42
804,2022,Zambia,Sub-Saharan Africa,developing,3.7600,0.930000,0.577000,0.306000,0.525000,0.203000,0.083000,60,35,40,50,30,42
805,2023,Zambia,Sub-Saharan Africa,developing,3.9820,0.914000,0.890000,0.095000,0.545000,0.189000,0.080000,60,35,40,50,30,42

In [10]:
df_data = pd.read_csv("C:\\users\范思源\Desktop\KM6312\KM6312.csv")

In [20]:
df_used = pd.get_dummies(df_data,columns=['region','developing_or_developed '])
df_used

,year,Country Name,happiness_score,gdp_per_capita,social_support,hearlthy_life_expentancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,PDI,...,region_East Asia,region_Latin America and Caribbean,region_Middle East and North Africa,region_North America and ANZ,region_South Asia,region_Southeast Asia,region_Sub-Saharan Africa,region_Western Europe,developing_or_developed _developed,developing_or_developed _developing
0,2015,Albania,4.9590,0.878670,0.804340,0.813250,0.357330,0.142720,0.064130,90,...,0,0,0,0,0,0,0,0,0,1
1,2016,Albania,4.6550,0.955300,0.501630,0.730070,0.318660,0.168400,0.053010,90,...,0,0,0,0,0,0,0,0,0,1
2,2017,Albania,4.6440,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,90,...,0,0,0,0,0,0,0,0,0,1
3,2018,Albania,4.5860,0.916000,0.817000,0.790000,0.419000,0.149000,0.032000,90,...,0,0,0,0,0,0,0,0,0,1
4,2019,Albania,4.7190,0.947000,0.848000,0.874000,0.383000,0.178000,0.027000,90,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801,2019,Zambia,4.1070,0.578000,1.058000,0.426000,0.431000,0.247000,0.087000,60,...,0,0,0,0,0,0,1,0,0,1
802,2020,Zambia,3.7594,0.536834,0.896037,0.363593,0.491318,0.250621,0.086705,60,...,0,0,0,0,0,0,1,0,0,1
803,2021,Zambia,4.0730,0.528000,0.552000,0.231000,0.487000,0.227000,0.074000,60,...,0,0,0,0,0,0,1,0,0,1
804,2022,Zambia,3.7600,0.930000,0.577000,0.306000,0.525000,0.203000,0.083000,60,...,0,0,0,0,0,0,1,0,0,1
805,2023,Zambia,3.9820,0.914000,0.890000,0.095000,0.545000,0.189000,0.080000,60,...,0,0,0,0,0,0,1,0,0,1

In [27]:
df_2=pd.DataFrame(df_used)
df_2.to_excel('KM6312_output.xlsx',index=False)